-- Pommy Foods - Database Schema
-- PostgreSQL Database Schema for Import
-- Generated from Prisma Schema
-- 
-- Usage:
--   1. Connect to your PostgreSQL database
--   2. Run this file: psql -U postgres -d your_database -f schema.sql
--   3. Or import via Supabase SQL Editor
--
-- Created: 2024
-- Database: PostgreSQL

-- Enable UUID extension (if needed for CUID)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- ENUMS
-- ============================================

CREATE TYPE "UserRole" AS ENUM (
    'SUPER_ADMIN',
    'ADMIN',
    'STORE_OWNER',
    'STORE_MANAGER',
    'KITCHEN_STAFF',
    'DRIVER'
);

CREATE TYPE "OrderStatus" AS ENUM (
    'DRAFT',
    'PENDING',
    'APPROVED',
    'KITCHEN_PREP',
    'READY',
    'IN_DELIVERY',
    'DELIVERED',
    'COMPLETED',
    'CANCELLED',
    'REJECTED'
);

CREATE TYPE "OrderType" AS ENUM (
    'MANUAL',
    'AUTO_REPLENISH'
);

CREATE TYPE "KitchenSheetStatus" AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'COMPLETED'
);

CREATE TYPE "DeliveryStatus" AS ENUM (
    'PENDING',
    'ASSIGNED',
    'IN_TRANSIT',
    'DELIVERED',
    'FAILED'
);

CREATE TYPE "ReturnStatus" AS ENUM (
    'PENDING',
    'PROCESSED',
    'REJECTED'
);

CREATE TYPE "InvoiceStatus" AS ENUM (
    'PENDING',
    'PARTIAL',
    'PAID',
    'OVERDUE',
    'CANCELLED'
);

CREATE TYPE "PaymentMethod" AS ENUM (
    'CASH',
    'DIRECT_DEBIT',
    'ONLINE_PAYMENT',
    'BANK_TRANSFER'
);

CREATE TYPE "NotificationType" AS ENUM (
    'ORDER_APPROVED',
    'ORDER_REJECTED',
    'DELIVERY_ASSIGNED',
    'PAYMENT_RECEIVED',
    'INVOICE_GENERATED',
    'STOCK_LOW',
    'TEMPERATURE_ALERT'
);

-- ============================================
-- TABLES
-- ============================================

-- Store Management
CREATE TABLE "Store" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "contactName" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "creditLimit" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "paymentTerms" INTEGER NOT NULL DEFAULT 30,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Store_pkey" PRIMARY KEY ("id")
);

-- User & Authentication
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "UserRole" NOT NULL,
    "storeId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdById" TEXT,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- Product Catalog
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "sku" TEXT NOT NULL,
    "description" TEXT,
    "price" DECIMAL(65,30) NOT NULL,
    "unit" TEXT NOT NULL DEFAULT 'unit',
    "category" TEXT,
    "shelfLife" INTEGER NOT NULL,
    "storageTempMin" DOUBLE PRECISION,
    "storageTempMax" DOUBLE PRECISION,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku");

-- Stock Management
CREATE TABLE "StoreStock" (
    "id" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "currentLevel" INTEGER NOT NULL,
    "threshold" INTEGER NOT NULL DEFAULT 10,
    "lastUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedBy" TEXT,

    CONSTRAINT "StoreStock_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "StoreStock_storeId_productId_key" ON "StoreStock"("storeId", "productId");
CREATE INDEX "StoreStock_storeId_idx" ON "StoreStock"("storeId");
CREATE INDEX "StoreStock_productId_idx" ON "StoreStock"("productId");

-- Order Management
CREATE TABLE "Order" (
    "id" TEXT NOT NULL,
    "orderNumber" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "createdById" TEXT NOT NULL,
    "status" "OrderStatus" NOT NULL DEFAULT 'DRAFT',
    "orderType" "OrderType" NOT NULL DEFAULT 'MANUAL',
    "totalAmount" DECIMAL(65,30) NOT NULL,
    "notes" TEXT,
    "autoGeneratedAt" TIMESTAMP(3),
    "approvedById" TEXT,
    "approvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Order_orderNumber_key" ON "Order"("orderNumber");

CREATE TABLE "OrderItem" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unitPrice" DECIMAL(65,30) NOT NULL,
    "totalPrice" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "OrderItem_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "OrderItem_orderId_idx" ON "OrderItem"("orderId");

-- Kitchen Management
CREATE TABLE "KitchenSheet" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "status" "KitchenSheetStatus" NOT NULL DEFAULT 'PENDING',
    "preparedBy" TEXT,
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "KitchenSheet_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "KitchenSheet_orderId_key" ON "KitchenSheet"("orderId");

CREATE TABLE "KitchenSheetItem" (
    "id" TEXT NOT NULL,
    "kitchenSheetId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "batchNumber" TEXT,
    "expiryDate" TIMESTAMP(3),
    "barcode" TEXT,
    "qrCode" TEXT,
    "isPacked" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "KitchenSheetItem_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "KitchenSheetItem_kitchenSheetId_idx" ON "KitchenSheetItem"("kitchenSheetId");

-- Delivery Management
CREATE TABLE "Delivery" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "driverId" TEXT,
    "status" "DeliveryStatus" NOT NULL DEFAULT 'PENDING',
    "scheduledDate" TIMESTAMP(3) NOT NULL,
    "deliveredAt" TIMESTAMP(3),
    "deliveryAddress" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "signature" TEXT,
    "deliveryPhoto" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Delivery_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Delivery_orderId_key" ON "Delivery"("orderId");

-- Temperature & Compliance
CREATE TABLE "TemperatureLog" (
    "id" TEXT NOT NULL,
    "deliveryId" TEXT,
    "storeId" TEXT NOT NULL,
    "temperature" DOUBLE PRECISION NOT NULL,
    "location" TEXT,
    "recordedBy" TEXT,
    "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isManual" BOOLEAN NOT NULL DEFAULT true,
    "sensorId" TEXT,
    "notes" TEXT,

    CONSTRAINT "TemperatureLog_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "TemperatureLog_deliveryId_idx" ON "TemperatureLog"("deliveryId");
CREATE INDEX "TemperatureLog_storeId_idx" ON "TemperatureLog"("storeId");
CREATE INDEX "TemperatureLog_recordedAt_idx" ON "TemperatureLog"("recordedAt");

-- Returns & Wastage
CREATE TABLE "Return" (
    "id" TEXT NOT NULL,
    "deliveryId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "returnedBy" TEXT NOT NULL,
    "returnDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" TEXT NOT NULL DEFAULT 'expired',
    "status" "ReturnStatus" NOT NULL DEFAULT 'PENDING',
    "processedAt" TIMESTAMP(3),
    "notes" TEXT,

    CONSTRAINT "Return_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ReturnItem" (
    "id" TEXT NOT NULL,
    "returnId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "expiryDate" TIMESTAMP(3) NOT NULL,
    "reason" TEXT NOT NULL DEFAULT 'expired',

    CONSTRAINT "ReturnItem_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ReturnItem_returnId_idx" ON "ReturnItem"("returnId");

-- Invoicing & Payments
CREATE TABLE "Invoice" (
    "id" TEXT NOT NULL,
    "invoiceNumber" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "subtotal" DECIMAL(65,30) NOT NULL,
    "discount" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "tax" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "returnAdjustment" DECIMAL(65,30) NOT NULL DEFAULT 0,
    "totalAmount" DECIMAL(65,30) NOT NULL,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "status" "InvoiceStatus" NOT NULL DEFAULT 'PENDING',
    "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "paidAt" TIMESTAMP(3),

    CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Invoice_invoiceNumber_key" ON "Invoice"("invoiceNumber");
CREATE UNIQUE INDEX "Invoice_orderId_key" ON "Invoice"("orderId");
CREATE INDEX "Invoice_storeId_idx" ON "Invoice"("storeId");
CREATE INDEX "Invoice_status_idx" ON "Invoice"("status");

CREATE TABLE "Payment" (
    "id" TEXT NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "deliveryId" TEXT,
    "amount" DECIMAL(65,30) NOT NULL,
    "paymentMethod" "PaymentMethod" NOT NULL,
    "paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transactionId" TEXT,
    "receiptUrl" TEXT,
    "collectedBy" TEXT,
    "notes" TEXT,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Payment_deliveryId_key" ON "Payment"("deliveryId");
CREATE INDEX "Payment_invoiceId_idx" ON "Payment"("invoiceId");

-- Notifications
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "relatedId" TEXT,
    "relatedType" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Notification_userId_idx" ON "Notification"("userId");
CREATE INDEX "Notification_isRead_idx" ON "Notification"("isRead");

-- ============================================
-- FOREIGN KEY CONSTRAINTS
-- ============================================

-- User Foreign Keys
ALTER TABLE "User" ADD CONSTRAINT "User_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- StoreStock Foreign Keys
ALTER TABLE "StoreStock" ADD CONSTRAINT "StoreStock_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StoreStock" ADD CONSTRAINT "StoreStock_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Order Foreign Keys
ALTER TABLE "Order" ADD CONSTRAINT "Order_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Order" ADD CONSTRAINT "Order_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- OrderItem Foreign Keys
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- KitchenSheet Foreign Keys
ALTER TABLE "KitchenSheet" ADD CONSTRAINT "KitchenSheet_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- KitchenSheetItem Foreign Keys
ALTER TABLE "KitchenSheetItem" ADD CONSTRAINT "KitchenSheetItem_kitchenSheetId_fkey" FOREIGN KEY ("kitchenSheetId") REFERENCES "KitchenSheet"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "KitchenSheetItem" ADD CONSTRAINT "KitchenSheetItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Delivery Foreign Keys
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_driverId_fkey" FOREIGN KEY ("driverId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Delivery" ADD CONSTRAINT "Delivery_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- TemperatureLog Foreign Keys
ALTER TABLE "TemperatureLog" ADD CONSTRAINT "TemperatureLog_deliveryId_fkey" FOREIGN KEY ("deliveryId") REFERENCES "Delivery"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TemperatureLog" ADD CONSTRAINT "TemperatureLog_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Return Foreign Keys
ALTER TABLE "Return" ADD CONSTRAINT "Return_deliveryId_fkey" FOREIGN KEY ("deliveryId") REFERENCES "Delivery"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Return" ADD CONSTRAINT "Return_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ReturnItem Foreign Keys
ALTER TABLE "ReturnItem" ADD CONSTRAINT "ReturnItem_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "Return"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReturnItem" ADD CONSTRAINT "ReturnItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Invoice Foreign Keys
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Payment Foreign Keys
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_deliveryId_fkey" FOREIGN KEY ("deliveryId") REFERENCES "Delivery"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================
-- COMMENTS
-- ============================================

COMMENT ON TABLE "User" IS 'User & Authentication - System users with role-based access';
COMMENT ON TABLE "Store" IS 'Store Management - Customer stores and locations';
COMMENT ON TABLE "Product" IS 'Product Catalog - Product catalog with pricing and specifications';
COMMENT ON TABLE "StoreStock" IS 'Stock Management - Stock levels per store-product pair';
COMMENT ON TABLE "Order" IS 'Order Management - Orders (manual and auto-generated)';
COMMENT ON TABLE "OrderItem" IS 'Order Items - Individual items within orders';
COMMENT ON TABLE "KitchenSheet" IS 'Kitchen Management - Kitchen preparation sheets';
COMMENT ON TABLE "KitchenSheetItem" IS 'Kitchen Sheet Items - Items to prepare with batch tracking';
COMMENT ON TABLE "Delivery" IS 'Delivery Management - Delivery tracking and execution';
COMMENT ON TABLE "TemperatureLog" IS 'Temperature & Compliance - Temperature readings for food safety';
COMMENT ON TABLE "Return" IS 'Returns & Wastage - Product returns and wastage tracking';
COMMENT ON TABLE "ReturnItem" IS 'Return Items - Individual items in returns';
COMMENT ON TABLE "Invoice" IS 'Invoicing & Payments - Invoice generation and tracking';
COMMENT ON TABLE "Payment" IS 'Payments - Payment records and methods';
COMMENT ON TABLE "Notification" IS 'Notifications - In-app notifications for users';

-- ============================================
-- SCHEMA COMPLETE
-- ============================================

-- This schema creates:
-- - 15 tables
-- - 8 enums
-- - All foreign key relationships
-- - All indexes for query optimization
-- - Cascade delete rules where appropriate

-- Next steps:
-- 1. Run this SQL file in your PostgreSQL database
-- 2. Run Prisma migrations: npm run db:migrate:deploy
-- 3. Seed initial data: npm run db:seed

