import { NextRequest, NextResponse } from "next/server"
import { requireRole } from "@/lib/auth-helpers"
import { DeliveryService } from "@/lib/services/delivery.service"
import { z } from "zod"

const autoGenerateSchema = z.object({
  scheduledDate: z.string().transform((str) => new Date(str)).optional().or(z.undefined()),
})

// POST /api/deliveries/auto-generate - Auto-generate deliveries for ready orders
export async function POST(request: NextRequest) {
  try {
    await requireRole(["SUPER_ADMIN", "ADMIN"], request)

    const body = await request.json().catch(() => ({}))
    const validatedData = autoGenerateSchema.parse(body)

    const result = await DeliveryService.autoGenerateDeliveries(
      validatedData.scheduledDate
    )

    return NextResponse.json(result)
  } catch (error) {
    if (error instanceof Error && (error.message === "Unauthorized" || error.message === "Forbidden")) {
      return NextResponse.json(
        { error: error.message },
        { status: error.message === "Unauthorized" ? 401 : 403 }
      )
    }

    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Invalid input", details: error.errors },
        { status: 400 }
      )
    }

    console.error("Error auto-generating deliveries:", error)
    return NextResponse.json(
      { error: "Failed to auto-generate deliveries" },
      { status: 500 }
    )
  }
}

